name: Atualizar Playlist e EPG TCL TV Plus

on:
  schedule:
    # Executa automaticamente todos os dias às 00:00 UTC (21:00 BRT)
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Permite rodar manualmente clicando no botão no GitHub

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Permissão para o bot atualizar os arquivos e o README

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Python ambiente
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependências de rede
      run: |
        python -m pip install --upgrade pip
        pip install requests urllib3

    - name: Executar o Raspador TCL
      run: python tcl_scraper.py

    - name: Injetar Data e Hora no Badge do README
      run: |
        # Força o README a voltar para o estado original do commit anterior se houver sujeira
        git checkout README.md
        
        # Coleta data e hora sem caracteres proibidos (Substitui ':' por 'h' e espaço por '%20')
        # Exemplo de resultado: 24-05-2026%20as%2023h52
        BRAZIL_TIME=$(TZ="America/Sao_Paulo" date +"%d-%m-%Y%20as%20%Hh%M")
        
        # Realiza a substituição limpa da palavra-chave
        sed -i "s/HORARIO_COMPILACAO/$BRAZIL_TIME/g" README.md

    - name: Salvar e Commitar alterações no repositório
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Adiciona os arquivos modificados
        git add tcl.m3u8 tcl_epg.xml README.md
        
        # Commita apenas se houver mudanças reais nos dados ou no horário
        if git diff --staged --quiet; then
          echo "Nenhuma alteração detectada."
        else
          git commit -m "Atualização automática: Dados e Timestamp atualizados"
          git push
        fi
